<a href="https://colab.research.google.com/github/JonathanLehner/Colab-collection/blob/master/copy_vertex_colors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# load hand scans and registrations
# the ones below are from the MANO dataset
# challenges: many of the scans suffer from bad lighting: white and black spots
# with the low resolution of the mesh this would look bad
# so need to be careful which scans to use
%cd /content/

!mkdir /content/vertex_colors

%cd /content/vertex_colors
!wget https://github.com/JonathanLehner/Colab-collection/releases/download/MANO/01_01r.ply
!wget https://github.com/JonathanLehner/Colab-collection/releases/download/MANO/01_01r_registration.ply  
!wget https://github.com/JonathanLehner/Colab-collection/releases/download/MANO/01_06r.ply
!wget https://github.com/JonathanLehner/Colab-collection/releases/download/MANO/01_06r_registration.ply
!wget https://github.com/JonathanLehner/Colab-collection/releases/download/MANO/01_22r.ply
!wget https://github.com/JonathanLehner/Colab-collection/releases/download/MANO/01_22r_registration.ply
!wget https://github.com/JonathanLehner/Colab-collection/releases/download/MANO/01_30r.ply
!wget https://github.com/JonathanLehner/Colab-collection/releases/download/MANO/01_30r_registration.ply 
  
!wget https://github.com/JonathanLehner/Colab-collection/releases/download/MANO/04_09r.ply
!wget https://github.com/JonathanLehner/Colab-collection/releases/download/MANO/04_09r_registration.ply 
  
!wget https://github.com/JonathanLehner/Colab-collection/releases/download/MANO/06_01r.ply
!wget https://github.com/JonathanLehner/Colab-collection/releases/download/MANO/06_01r_registration.ply
  
!wget https://github.com/JonathanLehner/Colab-collection/releases/download/MANO/09_01r.ply
!wget https://github.com/JonathanLehner/Colab-collection/releases/download/MANO/09_01r_registration.ply  
  
!wget https://github.com/JonathanLehner/Colab-collection/releases/download/MANO/10_07l.ply
!wget https://github.com/JonathanLehner/Colab-collection/releases/download/MANO/10_07l_registration.ply

%cd /content

/content
mkdir: cannot create directory ‘/content/vertex_colors’: File exists
/content/vertex_colors
--2019-05-19 18:41:48--  https://github.com/JonathanLehner/Colab-collection/releases/download/MANO/01_01r.ply
Resolving github.com (github.com)... 192.30.253.113
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github-production-release-asset-2e65be.s3.amazonaws.com/178957568/2f468b80-7767-11e9-8160-3993f6440e86?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20190519%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190519T184149Z&X-Amz-Expires=300&X-Amz-Signature=5eaf50599ce85f5c1baad0255d4c944dcf186625256252254b6b71cfb6b9ccb4&X-Amz-SignedHeaders=host&actor_id=0&response-content-disposition=attachment%3B%20filename%3D01_01r.ply&response-content-type=application%2Foctet-stream [following]
--2019-05-19 18:41:49--  https://github-production-release-asset-2e65be.s3.amazonaws.com/

In [2]:
import os
import trimesh
import numpy as np
import json

# collect hand meshes
hand_paths = []
num_hands = 0
for dirpath, dirnames, filenames in os.walk("/content/vertex_colors"):
    print(filenames)
    for filename in filenames:
        # only find hand scans, not registrations
        if(filename.endswith(".ply") and not filename.endswith("registration.ply")):
             path = os.path.join(dirpath, filename)
             hand_paths.append(path)        
             num_hands += 1
        
print(hand_paths)
print(num_hands)

['09_01r.ply', '01_30r_registration.ply', '04_09r.ply', '01_22r_registration.ply', '01_06r_registration.ply', '01_01r_registration.ply', '01_22r.ply', '09_01r_registration.ply', '06_01r_registration.ply', '10_07l_registration.ply', '10_07l.ply', '06_01r.ply', '04_09r_registration.ply', '01_30r.ply', '01_06r.ply', '01_01r.ply']
['/content/vertex_colors/09_01r.ply', '/content/vertex_colors/04_09r.ply', '/content/vertex_colors/01_22r.ply', '/content/vertex_colors/10_07l.ply', '/content/vertex_colors/06_01r.ply', '/content/vertex_colors/01_30r.ply', '/content/vertex_colors/01_06r.ply', '/content/vertex_colors/01_01r.ply']
8


In [6]:
# load the meshes
color_scans = np.zeros((num_hands,778,4))
for num_scan, hand_path in enumerate(hand_paths):
    hand_scan = trimesh.load(hand_path,process=False)
    hand_name = os.path.splitext(os.path.basename(hand_path))[0]
    print(hand_name)
    vertices_scan = hand_scan.vertices
    vertex_colors_scan = hand_scan.visual.vertex_colors
    print(len(hand_scan.vertices))
    hand_registration = trimesh.load('/content/vertex_colors/{0}_registration.ply'.format(hand_name),process=False)
    vertices_registration = hand_registration.vertices
    vertices_colors_registration = hand_registration.visual.vertex_colors
    print(len(hand_registration.vertices))

    pq = trimesh.proximity.ProximityQuery(hand_scan)
    colors = np.zeros((len(vertices_registration), 4))
    for num_vertex, vertex in enumerate(vertices_registration):
        #print("{0}: {1}".format(num_vertex, vertex)) 
        distance, vertex_id = pq.vertex(vertex)
        #print(vertex_id)
        color = vertex_colors_scan[vertex_id]
        # must transform this to be used for trimesh
        colors[num_vertex] = color #[color[0]/255, color[1]/255, color[2]/255]
        #print(color)

    print(colors)
    avg_color = np.mean(colors,axis=0)
    median_color = np.median(colors,axis=0)
    print("mean/median")
    print(avg_color)
    print(median_color)

    color_scans[num_scan] = colors
    # save to json file
    data = {}
    data['colors'] = colors.tolist()
    # add another color for the vertex at the wrist
    data['colors'].append(median_color.tolist())
    with open('/content/vertex_colors/colors_{0}.json'.format(hand_name), 'w') as outfile:  
        json.dump(data, outfile)
        
median_color = np.median(color_scans,axis=0)
print(median_color)
with open('/content/vertex_colors/colors_median.json', 'w') as outfile:  
        json.dump(data, outfile)

09_01r
48553
778
[[ 65.  49.  44. 255.]
 [ 69.  53.  46. 255.]
 [ 80.  57.  54. 255.]
 ...
 [ 71.  51.  45. 255.]
 [ 92.  60.  52. 255.]
 [ 58.  45.  38. 255.]]
mean/median
[143.21208226 100.97172237  85.9781491  255.        ]
[140.  94.  79. 255.]
04_09r
39319
778
[[ 26.  15.  15. 255.]
 [ 37.  23.  19. 255.]
 [ 35.  21.  18. 255.]
 ...
 [ 64.  47.  41. 255.]
 [ 82.  58.  55. 255.]
 [ 53.  38.  35. 255.]]
mean/median
[149.54498715 110.04241645  98.08354756 255.        ]
[146. 101.  89. 255.]
01_22r
47346
778
[[ 30.  29.  29. 255.]
 [ 45.  41.  37. 255.]
 [ 30.  29.  29. 255.]
 ...
 [ 30.  29.  29. 255.]
 [ 30.  29.  29. 255.]
 [ 13.  16.  14. 255.]]
mean/median
[107.18123393  83.68637532  73.89717224 255.        ]
[ 87.  65.  56. 255.]
10_07l
31144
778
[[ 74.  46.  37. 255.]
 [ 81.  54.  42. 255.]
 [ 60.  31.  23. 255.]
 ...
 [122.  77.  64. 255.]
 [141.  89.  78. 255.]
 [122.  86.  74. 255.]]
mean/median
[157.95372751 111.24807198  91.94087404 255.        ]
[151.  97.  78. 255.]
06_0

In [0]:
# visualisation somehow not working for the .ply files/should test if it is a general problem
# scene = trimesh.Scene([hand_scan])
# scene.show()
# scene = trimesh.Scene([hand_registration])
# scene.show()

